export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  comingSoon: '/coming-soon',
  forbidden: '/403',
  company: '/company',
  users: '/users',
  userNew: '/users/new',
  userDetail: '/users/:id',
  userEdit: '/users/:id/edit',
  employees: '/employees',
  employeeNew: '/employees/new',
  employeeDetail: '/employees/:id',
  employeeEdit: '/employees/:id/edit',
  branches: '/branches',
  branchNew: '/branches/new',
  branchDetail: '/branches/:id',
  branchEdit: '/branches/:id/edit',
  warehouses: '/warehouses',
  warehouseNew: '/warehouses/new',
  warehouseDetail: '/warehouses/:id',
  warehouseEdit: '/warehouses/:id/edit',
  vehicles: '/vehicles',
  vehicleNew: '/vehicles/new',
  vehicleDetail: '/vehicles/:id',
  vehicleEdit: '/vehicles/:id/edit',
  attendance: '/attendance',
  attendanceDetail: '/attendance/:id',
  leave: '/leave',
  leaveNew: '/leave/new',
  leaveDetail: '/leave/:id',
  leaveEdit: '/leave/:id/edit',
  cashAdvances: '/cash-advances',
  cashAdvanceNew: '/cash-advances/new',
  cashAdvanceDetail: '/cash-advances/:id',
  cashAdvanceEdit: '/cash-advances/:id/edit',
  payroll: '/payroll',
  payrollDetail: '/payroll/:id',
  transactions: '/transactions',
  transactionNew: '/transactions/new',
  transactionsDrafts: '/transactions/drafts',
  transactionDetail: '/transactions/:id',
  transactionEdit: '/transactions/:id/edit',
  transactionSettlement: '/transactions/:id/settlement',
  transactionReceipt: '/transactions/:id/receipt',
  trips: '/trips',
  tripsNew: '/trips/new',
  tripDetail: '/trips/:id',
  tripEdit: '/trips/:id/edit',
  expenses: '/expenses',
  expensesNew: '/expenses/new',
  expenseDetail: '/expenses/:id',
  expenseEdit: '/expenses/:id/edit',
  analytics: '/analytics',
  analyticsDashboard: '/analytics/dashboard',
  reports: '/reports',
  reportsTransactions: '/reports/transactions',
  reportsTrips: '/reports/trips',
  reportsExpenses: '/reports/expenses',
  reportsPayroll: '/reports/payroll',
  reportsAttendance: '/reports/attendance',
} as const

export const buildRoute = {
  userDetail: (id: string) => `/users/${id}`,
  userEdit: (id: string) => `/users/${id}/edit`,
  employeeDetail: (id: string) => `/employees/${id}`,
  employeeEdit: (id: string) => `/employees/${id}/edit`,
  branchDetail: (id: string) => `/branches/${id}`,
  branchEdit: (id: string) => `/branches/${id}/edit`,
  warehouseDetail: (id: string) => `/warehouses/${id}`,
  warehouseEdit: (id: string) => `/warehouses/${id}/edit`,
  vehicleDetail: (id: string) => `/vehicles/${id}`,
  vehicleEdit: (id: string) => `/vehicles/${id}/edit`,
  attendanceDetail: (id: string) => `/attendance/${id}`,
  leaveDetail: (id: string) => `/leave/${id}`,
  leaveEdit: (id: string) => `/leave/${id}/edit`,
  cashAdvanceDetail: (id: string) => `/cash-advances/${id}`,
  cashAdvanceEdit: (id: string) => `/cash-advances/${id}/edit`,
  payrollDetail: (id: string) => `/payroll/${id}`,
  transactionDetail: (id: string) => `/transactions/${id}`,
  transactionEdit: (id: string) => `/transactions/${id}/edit`,
  transactionSettlement: (id: string) => `/transactions/${id}/settlement`,
  transactionReceipt: (id: string) => `/transactions/${id}/receipt`,
  tripDetail: (id: string) => `/trips/${id}`,
  tripEdit: (id: string) => `/trips/${id}/edit`,
  expenseDetail: (id: string) => `/expenses/${id}`,
  expenseEdit: (id: string) => `/expenses/${id}/edit`,
} as const
